---
stages:
- name: BUILD
  inputs:
  - url: https://github.com/ibm-cloud-architecture/refarch-cloudnative-bff-inventory.git
    type: git
    branch: master
    dir_name: null
  properties:
  - name: BuildID
    value: ''
    type: text
  jobs:
  - name: Build
    type: builder
    working_dir: inventory
    artifact_dir: ''
    build_type: npm
    script: |
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: Team&Demo
      space: Dev
      application: Inventory_bff12345667678fdlkjdfsskljsd123
    script: |
      #!/bin/bash
      # Push app
      cf create-service Auto-Scaling free cloudnative-autoscale
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}" -n dev-${CF_APP_NAME}
      export APP_URL=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
